### ISSUE TITLE
impl error::Error for GolemError

### ISSUE THREAD

**Issue by vorner** [ryanisaacg/golem#25]
Hello

As suggested at https://github.com/ryanisaacg/quicksilver/pull/583#pullrequestreview-366768523, I wanted to implement the `Error` trait for `GolemError`.

However, it seems this is problematic. The issue is, this crate seems to be no-std and the `Error` trait is `std` only.

So I'd like to consult if there's a way forward. Add a `std` feature that would get enabled by `quicksilver` (because that one already depends on `std`)? Or is there a better way?

**Comment by elliegoldstein** [comment]
Adding a `std` feature seems like a good way forward 👍
