### ISSUE TITLE
Not compiling on stable/nightly win10

### ISSUE THREAD

**Issue by PvdBerg1998** [ryanisaacg/golem#32]
Hi, I'm using `quicksilver` and I'm hitting a compilation error in your crate.
There's several of the same errors in this file, so I will just list the first one:
```
golem-0.1.5\src\shader.rs:206:48
    |
206 |                     Int(x) => gl.uniform_1_i32(location, x),
    |                                                ^^^^^^^^ expected `&u32`, found 
`u32`
    |
    = note: expected enum `std::option::Option<&u32>`
               found enum `std::option::Option<u32>`
```

**Comment by PvdBerg1998** [comment]
It appears `glow` has changed to using references 6 months ago: https://github.com/grovesNL/glow/commit/45d4c1b6c38d3fdb7125d3425fba9c5bc437b014

**Comment by grovesNL** [comment]
Sorry about that – glow 0.4.1 is yanked now but 0.5.0 is still available if you'd like to use it in your PR

**Comment by elliegoldstein** [comment]
With the problematic glow version yanked, this shouldn't happen anymore. Thanks for fixing this everyone.
