### ISSUE TITLE
Incorrect behaviour when using shaders with differing attributes on WebGL

### ISSUE THREAD

**Issue by rburchell** [ryanisaacg/golem#35]
I have two shaders, defined as follows:

```
            Material::FlatColor => (
                vec![
                    Attribute::new("vert_position", AttributeType::Vector(D2)),
                ],
                vec![],
                vec![Uniform::new(
                    "uvert_color",
                    UniformType::Vector(NumberType::Float, D4),
                )],
                r#" void main() {
                        gl_Position = vec4(vert_position, 0, 1);
                }"#,
                r#" void main() {
                    gl_FragColor = uvert_color;
                }"#,
            ),
            Material::VertexColor => (
                vec![
                    Attribute::new("vert_position", AttributeType::Vector(D2)),
                    Attribute::new("vert_color", AttributeType::Vector(D4)),
                ],
                vec![Attribute::new("frag_color", AttributeType::Vector(D4))],
                vec![],
                r#" void main() {
                    gl_Position = vec4(vert_position, 0, 1);
                    frag_color = vert_color;
                }"#,
                r#" void main() {
                        gl_FragColor = frag_color;
                }"#,
            ),
```

I alternate in drawing things with these shaders. This works fine enough on desktop, but under WebGL, FlatColor doesn't appear. Checking the console gives me:

> WebGL: INVALID_OPERATION: drawElements: no buffer is bound to enabled attribute
WebGL: too many errors, no more errors will be reported to the console for this context.

Researching that sends me to:

https://stackoverflow.com/questions/36288389/when-should-i-enable-disable-vertex-position-attributes-in-webgl-opengl

Which implies (as I think is the case) that unused attributes should be disabled, and right now, golem doesn't appear to do that - it only enables used attributes.

Sure enough, if I add a dummy attribute replacing vert_color: 

                    Attribute::new("unused", AttributeType::Vector(D4)), (... and pad the buffers I'm using out, of course)

then flat color items are rendered as I expect.

**Comment by elliegoldstein** [comment]
Thanks for the detailed report / research!
