### ISSUE TITLE
GeometryMode could do with a way to set the line width/point size

### ISSUE THREAD

**Issue by rburchell** [ryanisaacg/golem#36]
A thought:

    enum GeometryMode {
        Points(f32),
        ...
        Lines(f32),
        LineStrip(f32),
        ...
    };

Internally, this could then translate to a call to glLineWidth (and maybe glPointSize) during draw_prepared.

**Comment by elliegoldstein** [comment]
These were intentionally left off, because unfortunately the standard does not specify any width other than `1.0` must be supported. It is for this reason [MDN recommends against setting `lineWidth`](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/lineWidth).

**Comment by rburchell** [comment]
Yes, I understand that support for them is patchy, but for environments where you know that it is supported, it can be convenient. At the least, my $0.02 is that I think that it should be _possible_ to accomplish this somehow even if it's not built in as-suggested - the current design of Context doesn't seem to really provide any way to do that, since there's no way to access the "underlying" context to do it yourself.

Anyway, consider this a "FYI" as a report of a problem I encountered while porting some stuff, I'll close this for now :)
