### ISSUE TITLE
scissors

### ISSUE THREAD

**Issue by knokko** [ryanisaacg/golem#40]
I noticed that you seem to support changing the `viewport`, but not the `scissor`. Is there any particular reason for this? Or did you just overlook it?

**Comment by elliegoldstein** [comment]
It wasn't something I had needed for my own use case, so I never implemented it.

**Comment by knokko** [comment]
It is indeed not something I would use often, so that makes sense.

However, I do believe that this is occasionally useful, so shall I make a pull request for this? Or could you do it yourself (it looks like adding this would take ~10 lines of code).

**Comment by elliegoldstein** [comment]
If you'd like to make a pull request, feel free. I'm not in need of this feature so I won't be implementing it myself
